[datastore.ambient_location-a]
class = "AmbientStore"
description = "Location A"
data.d1 = "location-a.living.temperature"
data.d2 = "location-a.living.humidity"
data.d3 = "location-a.external.temperature"
data.d4 = "location-a.external.humidity"
data.d5 = "location-a.kitchen.temperature"
data.d6 = "location-a.kitchen.humidity"
data.d7 = "location-a.bedroom.temperature"
data.d8 = "location-a.bedroom.humidity"

[datastore.ambient_location-b]
class = "AmbientStore"
description = "Location B"
data.d1 = "location-b.living.temperature"
data.d2 = "location-b.living.humidity"
data.d3 = "location-b.external.temperature"
data.d4 = "location-b.external.humidity"
data.d7 = "location-b.bedroom.temperature"
data.d8 = "location-b.bedroom.humidity"

[datastore.ambient_meters]
class = "AmbientStore"
description = "BHT-Meters"
data.d1 = "location-a.pressure"
data.d2 = "location-a.temperature"
data.d3 = "location-a.humidity"
data.d4 = "location-a.power"
data.d5 = "location-b.pressure"
data.d6 = "location-b.temperature"
data.d7 = "location-b.humidity"
data.d8 = "location-b.power"

[datastore.alternate_meters]
class = "AmbientStore"
description = "BHT-Meters"
data.d1 = "location-b.pressure"
data.d2 = "location-b.temperature"
data.d3 = "location-b.humidity"
data.d4 = "location-b.power"
data.d5 = "location-a.pressure"
data.d6 = "location-a.temperature"
data.d7 = "location-a.humidity"
data.d8 = "location-a.power"

[datastore.alternate_location-b]
class = "AmbientStore"
description = "Location B"
data.d1 = "location-b.living.temperature"
data.d2 = "location-b.living.humidity"
data.d3 = "location-b.external.temperature"
data.d4 = "location-b.external.humidity"
data.d7 = "location-b.bedroom.temperature"
data.d8 = "location-b.bedroom.humidity"

[datastore.alternate_location-a]
class = "AmbientStore"
description = "Location A"
data.d1 = "location-a.living.temperature"
data.d2 = "location-a.living.humidity"
data.d3 = "location-a.external.temperature"
data.d4 = "location-a.external.humidity"
data.d5 = "location-a.kitchen.temperature"
data.d6 = "location-a.kitchen.humidity"
data.d7 = "location-a.bedroom.temperature"
data.d8 = "location-a.bedroom.humidity"

[sensor.location-a_living]
class = "SwitchbotTH"
ble.macaddr = "F4:98:41:C0:54:C7"
description = "Living Room"
data.temperature = "location-a.living.temperature"
data.humidity = "location-a.living.humidity"

[sensor.location-a_external]
class = "SwitchbotTH"
ble.macaddr = "D5:3F:69:C5:47:07"
description = "External"
data.temperature = "location-a.external.temperature"
data.humidity = "location-a.external.humidity"

[sensor.location-a_kitchen]
class = "SwitchbotTH"
ble.macaddr = "E4:FA:33:7C:E8:9E"
description = "Kitchen"
data.temperature = "location-a.kitchen.temperature"
data.humidity = "location-a.kitchen.humidity"

[sensor.location-a_bedroom]
class = "SwitchbotTH"
ble.macaddr = "E3:F1:06:D3:6C:F7"
description = "Bedroom"
data.temperature = "location-a.bedroom.temperature"
data.humidity = "location-a.bedroom.humidity"

[sensor.location-a_plug_living]
class = "SwitchbotPlug"
ble.macaddr = "60:55:F9:2A:4A:6A"
wifi.macaddr = "60:55:F9:2A:4A:68"
description = "Living"
data.power = "location-a.power"

[sensor.location-a_bme280]
class = "BoshBME280"
i2c.bus = 1
i2c.address = 0x76
description = "Location A Meter"
data.pressure = "location-a.pressure"
data.temperature = "location-a.temperature"
data.humidity = "location-a.humidity"

[sensor.location-b_bme280]
disabled = true
class = "BoshBME280"
i2c.bus = 1
i2c.address = 0x76
description = "Location B Meter"
data.pressure = "location-b.pressure"
data.temperature = "location-b.temperature"
data.humidity = "location-b.humidity"
